import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
padding.x = 5
padding.y = 5 

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 14
